# Generated by Django 4.2.2 on 2023-06-18 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_manga'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='cover_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
