# Generated by Django 4.2.2 on 2023-08-10 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_manga_cover_url_alter_manga_score'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='ToDoList',
        ),
    ]
